version: '3'

services:

  db:
    image: postgres:13
    container_name: rd01
    environment:
      - POSTGRES_DB=distribution_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
       - "5431:5432"

  broker:
    image: redis
    ports:
       - "6378:6379"
    restart: always
